services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883"
    restart: no

  ble-service:
    build: ./ble-service
    container_name: ble-service
    depends_on:
      - mqtt
      
    devices:
      - "/dev/rfcomm0:/dev/rfcomm0"

      
    restart: no         
           



  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mqtt       
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data

    restart: no

