services:
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
    healthcheck:
      # Usamos mosquitto_check_version o un ping nativo silencioso en lugar de nc
      test: ["CMD-SHELL", "mosquitto_sub -t '$SYS/broker/version' -C 1 -E -i healthcheck-client || exit 1"]
      interval: 10s # Subimos a 10s para dar estabilidad en el arranque de la Raspberry
      timeout: 3s
      retries: 5

  ble-service:
    build: ./ble-service
    container_name: ble-service
    restart: unless-stopped
    privileged: true 
    volumes:
      # 🔥 CORREGIDO: Eliminado el :ro. Python necesita permisos de escritura para abrir el puerto serial
      - /dev:/dev 
    stop_grace_period: 3s 
    depends_on:
      mqtt:
        condition: service_healthy

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      mqtt:
        condition: service_healthy 
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./data:/app/data
    restart: unless-stopped