persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# Permite conexiones desde otros contenedores
listener 1883 0.0.0.0
allow_anonymous true

# Puerto exclusivo para que el navegador HTML reciba datos en tiempo real
listener 9001
protocol websockets